### PR TITLE
Fix bug detect ArrayBuffer is incorrectly

### PR DESCRIPTION
**Pull request by yanghoxom**
ArrayBuffer.isView does not work for ArrayBuffer
it will return `false` it only returns true for TypedArray or DataView (like Int32Arrray)
image

ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/isView#using_isview

### CODE REVIEW

**Comment by zurmokeeper** [comment]
@yanghoxom Can you add some test cases so that the problem can be better verified

**Comment by yanghoxom** [comment]
@zurmokeeper I updated some test cases to use ArrayBuffer to test. It ok for you?

**Comment by zurmokeeper** [comment]
@yanghoxom Thank you very much. I'll take a look.

**Comment by yanghoxom** [comment]
@zurmokeeper  sorry for bothering you, How is it going? I am still waiting for this fix

**Comment by zurmokeeper** [comment]
@yanghoxom I'm sorry, I've been really busy lately. Can you provide me with your excel please? I want to write one more test case with your excel and then it will work fine under your pr, I have been hesitating before, also I am worried that the previous test case is not safe enough and I am afraid that it will affect the previous version, please forgive me.

**Comment by yanghoxom** [comment]
@zurmokeeper Thank you so much, this is my file 
the password is 123456
[pass.xlsx](https://github.com/zurmokeeper/officecrypto-tool/files/13972164/pass.xlsx)

**Comment by zurmokeeper** [comment]
@yanghoxom 

I tried this code to decrypt your excel, or are you getting an error reading this encrypted excel on the front end and can't decrypt it?

```
const officeCrypto = require('officecrypto-tool');
const fs = require('fs').promises;

//decrypt a file with a password
(async ()=>{
        const input = await fs.readFile(`pass.xlsx`);
        const output = await officeCrypto.decrypt(input, {password: '123456'});
        await fs.writeFile(`out_success.xlsx`, output);
})();
```

**Comment by yanghoxom** [comment]
@zurmokeeper Yes, I got an error on the front end
on the front end, the data which I get from the input is ArrayBuffer
it is not about the decrypt logic, `ArrayBuffer.isView(input)` return false if input is ArrayBuffer

**Comment by zurmokeeper** [comment]
@yanghoxom Can you provide the key code for your front end? Read the files and convert those, or provide the next minimal reproduction example, because here I have encountered someone else with the same query before, also with the front-end code, and at that time it was the front-end code that wasn't written correctly, and there were some key codes that were faulty.

**Comment by yanghoxom** [comment]
@zurmokeeper https://stackblitz-starters-cvzezw.stackblitz.io
this is a minimal reproduction example, it throw an error immediately when you choose a file

**Comment by yanghoxom** [comment]
@zurmokeeper 
https://stackblitz-starters-cvzezw.stackblitz.io
thank you, this is a minimal reproduction example.

**Comment by zurmokeeper** [comment]
@yanghoxom Can't you see the code on this one?

image

**Comment by yanghoxom** [comment]
@zurmokeeper i'm sorry, this one https://stackblitz.com/edit/stackblitz-starters-cvzezw?file=src%2FApp.js

**Comment by zurmokeeper** [comment]
@yanghoxom 
image

If you're in a hurry, you can use this as a temporary treatment first. I tried it and it works fine. Follow-up in order to be compatible with the previous someone has been used in this way, pr I may change, change to the following:

if(ArrayBuffer.isView(input) || data instanceof ArrayBuffer)

This way ArrayBuffer or TypedArray or DataView can be used normally.

**Comment by yanghoxom** [comment]
@zurmokeeper thank you, I will try it

**Review by zurmokeeper — APPROVED** [review]

**Comment by zurmokeeper** [comment]
@yanghoxom The new version has been released, just update the version, thanks again!

**Pull request merged**
