### PR TITLE
fix: ppt file with pictures

### PR DESCRIPTION
**Pull request by guillenotfound**
As per the reference implementation in Python: https://github.com/nolze/msoffcrypto-tool/blob/85ff05be8c057dac51fcd5b12f15fc438df5f1ab/msoffcrypto/format/ppt97.py#L798

The original streams are copied and replaced with the newly decrypted ones.

With this fix in place I'm able to visualize the file in [pdftron](https://demo.pdftron.com/demo/), **but this fix won't fix the fact that the original file and the resulting one will be different** and we won't be able to visualize images in the decrypted ppt file, that's something I don't know how to fix, I guess we need to apply decryption in chunks for the pictures stream?

image

pwd: `Password@123`
[ppt.zip](https://github.com/user-attachments/files/16510216/ppt.zip)

### CODE REVIEW

**Comment by zurmokeeper** [comment]
@guillenotfound It's possible, I used WPS to decrypt the encrypted file you gave me, and after I decrypted it, I got a different 'Pictures' stream in the file than when it was encrypted, so it's possible that something was done here.

**Comment by zurmokeeper** [comment]
@guillenotfound #19 This issue mentions the decryption of ppt Pictures stream, there is a partial implementation of golang, maybe it will help you, if it can inspire you to finish decrypting ppt Pictures stream, PR will be perfect.

**Comment by zurmokeeper** [comment]
@guillenotfound 

Would it be possible to guillenotfound:patch-2 branch to synchronize the latest main branch first? I'm afraid that there will be a conflict during the PR merge.

**Comment by guillenotfound** [comment]
> @guillenotfound
> 
> Would it be possible to guillenotfound:patch-2 branch to synchronize the latest main branch first? I'm afraid that there will be a conflict during the PR merge.

Done! I cannot promise I'll be able to add images support, but if we get a complete code snippet I'll be happy to try :)

At least this one will allow rendering in some platforms even if we don't see the images (we'll have parity with Python script)

**Review by CTyrannosaurus — APPROVED** [review]

**Comment by zurmokeeper** [comment]
@guillenotfound v0.0.16 Released

**Pull request merged**
